# Site settings
title: Pavel K. - Analytics Engineer & DWH System Analys
description: Personal page of Pavel K. - Analytics Engineer & DWH System Analys
author: Pavel K.
email: explain@analyze.dev
url: ""
baseurl: ""

# Build settings
markdown: kramdown
permalink: none

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - old

# Default values
defaults:
  - scope:
      path: ""
    values:
      layout: default
